name: Update README

on:
    schedule:
    - cron: '*/30 * * * *'
    workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Update README
        run: |
          echo "Updating README..."
